# Generated by Django 5.0.2 on 2024-02-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_listingimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='license',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
